name: Make
on:
  push:
    branches: [ master ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: lukka/get-cmake@v3.22.2
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G"MinGW Makefiles" ..
          mingw32-make
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/build